name: rpnhs

dependencies:
- base >= 4.7 && < 5
- array
- containers
- errors
- haskeline
- optparse-applicative

library:
  source-dirs: src

executables:
  rpnhs:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rpnhs

tests:
  rpnhs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rpnhs
